[package]
name = "pdl"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
codespan-reporting = "*"
pest = "*"
pest_derive = "*"
proc-macro2 = "*"
quote = "*"
serde = { version = "*", features = ["default", "derive", "serde_derive", "std"] }
serde_json = "*"
structopt = "*"
syn = "*"

[dev-dependencies]
tempfile = "*"
